class Style:
    """Encapsulates the CSS stylesheet rules for pyaidoc HTML pages."""

    def text(self) -> str:
        return (
            ":root {\n"
            "  --font-size-base: 15px;\n"
            "  --font-size-min: 14px;\n"
            "  --bg-color: #f8fafc;\n"
            "  --card-bg: #ffffff;\n"
            "  --text-main: #0f172a;\n"
            "  --text-muted: #64748b;\n"
            "  --border-color: #e2e8f0;\n"
            "  --primary: #2563eb;\n"
            "  --badge-req-bg: #fee2e2;\n"
            "  --badge-req-text: #991b1b;\n"
            "  --badge-opt-bg: #f1f5f9;\n"
            "  --badge-opt-text: #475569;\n"
            "}\n"
            "@media (prefers-color-scheme: dark) {\n"
            "  :root {\n"
            "    --bg-color: #0b0f17;\n"
            "    --card-bg: #161e2e;\n"
            "    --text-main: #f8fafc;\n"
            "    --text-muted: #94a3b8;\n"
            "    --border-color: #27354a;\n"
            "    --primary: #3b82f6;\n"
            "    --badge-req-bg: #450a0a;\n"
            "    --badge-req-text: #fca5a5;\n"
            "    --badge-opt-bg: #1e293b;\n"
            "    --badge-opt-text: #94a3b8;\n"
            "  }\n"
            "}\n"
            "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
            "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: var(--font-size-base); background: var(--bg-color); color: var(--text-main); line-height: 1.6; padding: 2rem 1rem; }\n"
            ".pyaidoc-container { max-width: 900px; margin: 0 auto; }\n"
            ".pyaidoc-header { margin-bottom: 2rem; border-bottom: 1px solid var(--border-color); padding-bottom: 1.5rem; }\n"
            ".pyaidoc-header h1 { font-size: 1.75rem; font-weight: 700; color: var(--text-main); margin-bottom: 0.5rem; }\n"
            ".pyaidoc-subtitle { color: var(--text-muted); font-size: var(--font-size-base); }\n"
            ".pyaidoc-cards { display: flex; flex-direction: column; gap: 1.5rem; }\n"
            ".pyaidoc-card { background: var(--card-bg); border: 1px solid var(--border-color); border-radius: 8px; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }\n"
            ".pyaidoc-card-title { font-size: 1.2rem; font-weight: 600; color: var(--primary); margin-bottom: 0.5rem; }\n"
            ".pyaidoc-card-desc { color: var(--text-muted); font-size: var(--font-size-min); margin-bottom: 1.25rem; white-space: pre-line; }\n"
            ".pyaidoc-table { width: 100%; border-collapse: collapse; font-size: var(--font-size-min); margin-top: 0.5rem; }\n"
            ".pyaidoc-table th, .pyaidoc-table td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border-color); }\n"
            ".pyaidoc-table th { background: var(--bg-color); font-weight: 600; color: var(--text-muted); }\n"
            ".pyaidoc-type { color: #d97706; font-family: monospace; font-size: var(--font-size-min); }\n"
            ".pyaidoc-badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: var(--font-size-min); font-weight: 500; }\n"
            ".pyaidoc-badge.req { background: var(--badge-req-bg); color: var(--badge-req-text); }\n"
            ".pyaidoc-badge.opt { background: var(--badge-opt-bg); color: var(--badge-opt-text); }\n"
            ".pyaidoc-empty, .pyaidoc-no-params { color: var(--text-muted); font-size: var(--font-size-min); font-style: italic; }\n"
        )

    def __str__(self) -> str:
        return self.text()
